### ISSUE TITLE
refactor usage of elastic scroll API

### ISSUE THREAD

**Issue by revolunet** [SocialGouv/cdtn-monolog#154]
Looks like this will soon be deprecated : https://www.elastic.co/guide/en/elasticsearch/reference/7.15/scroll-api.html

meanwhile we should ensure to use `clearScroll` https://stackoverflow.com/questions/63488627/how-to-resolve-trying-to-create-too-many-scroll-contexts-must-be-less-than-or-e

**Comment by m-maillot** [comment]
Top, j'allais créer l'issue :) 

Du coup je propose de basculer sur l'utilisation du search_after https://www.elastic.co/guide/en/elasticsearch/reference/7.15/paginate-search-results.html#search-after

Je l'ajoute au kanban de CDTN car c'est un point critique pour le projet et il faut qu'on le traite pour ne pas rencontrer à nouveau le soucis.
