### ISSUE TITLE
Switch from search_after to scroll queries 

### ISSUE THREAD

**Issue by Armandgrd** [SocialGouv/cdtn-monolog#166]
The way ES is queried limits results to 10K per doc, in order to havoid this we need to refactor the [getDocumentFromEs](https://github.com/SocialGouv/cdtn-monolog/blob/037ab2065a423ca152a9956e797b5de7804898c3/src/es/elastic.ts#L34) function in order to use [scroll queries](https://www.elastic.co/guide/en/elasticsearch/reference/7.17/scroll-api.html)

**Comment by m-maillot** [comment]
Traitement réalisé
