### ISSUE TITLE
Rapports de requête

### ISSUE THREAD

**Issue by rmelisson** [SocialGouv/cdtn-monolog#77]
Calcul et publication à interval régulier des "query reports".

Étapes :
- récupérer les logs de recherche pour une période donnée
- créer un cache du moteur via une instance de l'API (master ou déploiement dédié ?) : merge des "clusters"
- évaluer chaque visite unique : identifier les requêtes de recherche et les visites de contenu associé, compter les itérations.

- publier un rapport par requête avec : 
  - query cluster : chaque requête (+ occurence) menant à une liste commune de résultats
  - liste des résultats : chaque résultat retourné par le moteur avec son click rank + algo (search / semantic / prequalified)
  - métriques : dcg / idcg / ndcg 

- documenter leur utilisation / consultation via Kibana / Monolog

Exemple de rapport de requête : 
![Screenshot 2020-09-28 at 16 48 48](https://user-images.githubusercontent.com/752778/94447825-86a59a00-01aa-11eb-87db-11f8c70185c9.png)

**Comment by virginielastisneres** [comment]
@rmelisson Rémi cette issue peut être clôturée non ? c'est ton travail que tu as fais avec les 2 excels sur les requêtes préqualifiées et requêtes search ?

**Comment by rmelisson** [comment]
yep
